version: "3.9"

services:
  fastapi:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CORS_ORIGINS=["*"]
      - CORS_CREDENTIALS=True
      - CORS_METHODS=["*"]
      - CORS_HEADERS=["*"]
    ports:
      - 8000:8000

  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
